package com.acumengroup.greekmain.core.constants;

public interface LabelConfig {


    String VERSION_NO="1.0.1.10";
    String QT_CALL_OPT_TYPE = "QT_CALL_OPT_TYPE";
    String QT_PUT_OPT_TYPE = "QT_PUT_OPT_TYPE";
    String TD_LIMIT_ORDER_TYPE = "TD_LIMIT_ORDER_TYPE";
    String TD_MARKET_ORDER_TYPE = "TD_MARKET_ORDER_TYPE";
    String TD_AMO_ORDER_LIFE = "TD_AMO_ORDER_LIFE";
    String TD_DAY_ORDER_LIFE = "TD_DAY_ORDER_LIFE";
    String TD_IOC_ORDER_LIFE = "TD_IOC_ORDER_LIFE";
    String TD_GTC_ORDER_LIFE = "TD_GTC_ORDER_LIFE";
    String TD_GTD_ORDER_LIFE = "TD_GTD_ORDER_LIFE";
    String TD_INTRADAY_PRODUCT_TYPE = "TD_INTRADAY_PRODUCT_TYPE";
    String TD_DELIVERY_PRODUCT_TYPE = "TD_DELIVERY_PRODUCT_TYPE";
    String TD_VALUE_PLUS_PRODUCT_TYPE = "TD_VALUE_PLUS_PRODUCT_TYPE";
    String TD_MARGIN_PLUS_ORDER_TYPE = "TD_MARGIN_PLUS_ORDER_TYPE";
    String TD_HEADER_TXT = "TD_HEADER_TXT";
    String TD_SYMBOL_EMPTY_MSG = "TD_SYMBOL_EMPTY_MSG";
    String TD_QTY_EMPTY_MSG = "TD_QTY_EMPTY_MSG";
    String TD_PRICE_EMPTY_MSG = "TD_PRICE_EMPTY_MSG";
    String TD_TRIG_PRICE_EMPTY_MSG = "TD_TRIG_PRICE_EMPTY_MSG";
    String GREEK_MENU_PORTFOLIO_TXT = "GREEK_MENU_PORTFOLIO_TXT";
    String GREEK_MENU_DASHBOARD_TXT = "GREEK_MENU_DASHBOARD_TXT";
    String GREEK_MENU_MYREPORT_TXT = "GREEK_MENU_REPORT_TXT";
    String GREEK_MENU_EDIS_TXT = "GREEK_MENU_EDIS_TXT";
    String GREEK_MENU_FIIDIIACTIVITIES = "GREEK_MENU_FIIDIIACTIVITIES";
    String GREEK_MENU_CHARTING = "GREEK_MENU_CHARTING";
    String GREEK_MENU_CHATMESSAGE = "GREEK_MENU_CHATMESSAGE";
    String GREEK_MENU_SETTINGS_TXT = "GREEK_MENU_SETTINGS_TXT";
    String GREEK_MENU_PROFILE_TXT = "GREEK_MENU_PROFILE_TXT";
    String GREEK_MENU_LAS_TXT = "GREEK_MENU_LAS_TXT";
    String GREEK_MENU_MORE_TXT = "GREEK_MENU_MORE_TXT";
    String GREEK_MENU_HELP_TXT = "GREEK_MENU_HELP_TXT";
    String GREEK_MENU_ABOUT_TXT = "GREEK_MENU_ABOUT_TXT";
    //Portfolio Submenu
    String GREEK_MENU_MYSTOCKS_TXT = "GREEK_MENU_MYSTOCKS_TXT";
    String GREEK_MENU_WATCHLIST_TXT = "GREEK_MENU_WATCHLIST_TXT";
    String GREEK_MENU_LASTVISITED_TXT = "GREEK_MENU_LASTVISITED_TXT";

    //Trade Submenu
    String GREEK_MENU_ORDERFORM_TXT = "GREEK_MENU_ORDERFORM_TXT";

    //Report Submenu
    String GREEK_MENU_LEDGER_TXT = "GREEK_MENU_LEDGER_TXT";
    String GREEK_MENU_TRANSACTION_TXT = "GREEK_MENU_TRANSACTION_TXT";
    String GREEK_MENU_P_L_TXT = "GREEK_MENU_P_L_TXT";
    String GREEK_MENU_HOLDING_TXT = "GREEK_MENU_HOLDING_TXT";
    String GREEK_MENU_SAUDA_TXT = "GREEK_MENU_SAUDA_TXT";
    String GREEK_MENU_COMBINED_LEDGER = "GREEK_MENU_COMBINED_LEDGER";
    String GREEK_MENU_COST_REPORT = "GREEK_MENU_COST_REPORT";
    String GREEK_MENU_INTEREST_REPORT = "GREEK_MENU_INTEREST_REPORT";
    String GREEK_MENU_LOAN_AGAINST_REPORT = "GREEK_MENU_LOAN_AGAINST_REPORT";
    String GREEK_MENU_PROFIT_AND_LOSS = "GREEK_MENU_F&O_PROFIR_AND_LOSS";
    String GREEK_MENU_CASH_PROFIT_AND_LOSS = "GREEK_MENU_CASH_PROFIT_AND_LOSS";

    String GREEK_MENU_EDIS_DASHBOARD = "GREEK_MENU_EDIS_DASHBOARD";
    String GREEK_MENU_MARGIN_PLEDGE = "GREEK_MENU_MARGIN_PLEDGE";
    String GREEK_MENU_MARGIN_PLEDGE_DASHBOARD = "GREEK_MENU_MARGIN_PLEDGE_DASHBOARD";
    String GREEK_MENU_EDIS_TRANSACTION_DETAILS = "GREEK_MENU_EDIS_TRANSACTION_DETAILS";


    String GREEK_MENU_FEEDBACK_TXT = "GREEK_MENU_LEDGER_TXT";
    String GREEK_MENU_SHARE_TXT = "GREEK_MENU_TRANSACTION_TXT";
    String GREEK_MENU_ABOUTUS_TXT = "GREEK_MENU_P_L_TXT";
    String GREEK_MENU_VERSION_TXT = "GREEK_MENU_VERSION_TXT";



    String GREEK_MENU_ORDERBOOK_TXT = "GREEK_MENU_ORDERBOOK_TXT";
    String GREEK_MENU_TRADE_BOOK_TXT = "GREEK_MENU_TRADE_BOOK_TXT";
    String GREEK_MENU_NETPOSITION_TXT = "GREEK_MENU_NETPOSITION_TXT";
    String GREEK_MENU_MARGIN_TXT = "GREEK_MENU_MARGIN_TXT";
    String GREEK_MENU_DEMAT_HOLDING_TXT = "GREEK_MENU_DEMAT_HOLDING_TXT";
    String GREEK_MENU_DEMAT_HOLDING_SINGLE_TXT = "GREEK_MENU_DEMAT_HOLDING_SINGLE_TXT";
    String GREEK_MENU_CHANGE_THEME_TXT = "GREEK_MENU_CHANGE_THEME_TXT";
    //Main Group
    String GREEK_MENU_TRADE_TXT = "GREEK_MENU_TRADE_TXT";
    String GREEK_MENU_MARKET_TXT = "GREEK_MENU_MARKET_TXT";
    String GREEK_MENU_BOTTOM_MARKET_TXT = "GREEK_MENU_BOTTOM_MARKET_TXT";
    String GREEK_MENU_BOTTOM_ORDER_TXT = "GREEK_MENU_BOTTOM_ORDER_TXT";
    String GREEK_MENU_BOTTOM_PORTFOLIO_TXT = "GREEK_MENU_BOTTOM_PORTFOLIO_TXT";
    String GREEK_BACK_OFFICE_LINKS_TXT = "GREEK_BACK_OFFICE_LINKS_TXT";
    String GREEK_OFFLINE_BANK_LINKS_TXT = "GREEK_OFFLINE_BANK_LINKS_TXT";

    String GREEK_MENU_STRATEGY_TXT = "GREEK_MENU_STRATEGY_TXT";
    String GREEK_MENU_STRATEGY_BUILDER_TXT = "GREEK_MENU_STRATEGY_BUILDER_TXT";
    String GREEK_MENU_NEWS_TXT = "GREEK_MENU_NEWS_TXT";
    String GREEK_MENU_NEWSS_TXT = "GREEK_MENU_NEWSS_TXT";
    String GREEK_MENU_LOGOUT_TXT = "GREEK_MENU_LOGOUT_TXT";
    String GREEK_MENU_LOGIN_TO_TRADE_TXT = "GREEK_MENU_LOGIN_TO_TRADE_TXT";
    String GREEK_MENU_EXIT = "GREEK_MENU_EXIT";
    String GREEK_MENU_GUEST_LOGOUT_TXT = "GREEK_MENU_GUEST_LOGOUT_TXT";
    String GREEK_MENU_LOGIN_AS_GUEST_TXT = "GREEK_MENU_LOGIN_AS_GUEST_TXT";
    String OR_ORDER_STATUS_BTN = "OR_ORDER_STATUS_BTN";
    String OR_NEW_ORDER_BTN = "OR_NEW_ORDER_BTN";
    String OR_SUCCESS_STATUS = "OR_SUCCESS_STATUS";
    String CP_OLD_PASSWORD_EMPTY_MSG = "CP_OLD_PASSWORD_EMPTY_MSG";
    String CP_NEW_PASSWORD_EMPTY_MSG = "CP_NEW_PASSWORD_EMPTY_MSG";
    String CP_OLD_NEW_SAME_MSG = "CP_OLD_NEW_SAME_MSG";
    String FNO_LTP_TXT = "FNO_LTP_TXT";
    String FNO_VOLUME = "FNO_VOLUME";
    String FNO_CHANGE_TXT = "FNO_CHANGE_TXT";
    String FNO_CHANGE_PER_TXT = "FNO_CHANGE_PER_TXT";
    String GREEK_SEBI_LINKS_TXT = "GREEK_SEBI_LINKS_TXT";
    String GREEK_NSE_LINKS_TXT = "GREEK_NSE_LINKS_TXT";
    String GREEK_BSE_LINKS_TXT = "GREEK_BSE_LINKS_TXT";
    String GREEK_SSL_LINKS_TXT = "GREEK_SSL_LINKS_TXT";
    String GREEK_MCX_LINKS_TXT = "GREEK_MCX_LINKS_TXT";
    String GREEK_NCDEX_LINKS_TXT = "GREEK_NCDEX_LINKS_TXT";
    String GREEK_MENU_MUTFUNDS_TXT = "GREEK_MENU_MUTFUNDS_TXT";

    //Setting Menu

    String GREEK_MENU_APP_SETTING_TXT = "GREEK_MENU_APP_SETTING_TXT";
    String GREEK_MENU_CHANGE_PASSWORD_TXT = "GREEK_MENU_CHANGE_PASSWORD_TXT";
    String GREEK_MENU_RECOMMENDATION_TXT = "GREEK_MENU_RECOMMENDATION_TXT";
    String GREEK_MENU_NOTIFICATIONS_TXT = "GREEK_MENU_NOTIFICATIONS_TXT";
    String GREEK_MENU_LINKS = "GREEK_MENU_LINKS";
    String GREEK_MENU_IPO = "GREEK_MENU_IPO";
    String GREEK_MENU_ALERTS = "GREEK_MENU_ALERTS";

    String GREEK_MENU_FUND_TRANSFER = "GREEK_MENU_FUND_TRANSFER";
    String GREEK_MENU_FUND_TRANSFER_TXT = "GREEK_MENU_FUND_TRANSFER_TXT";
    String GREEK_MENU_FUND_TRANSFER_DETAILS_TXT = "GREEK_MENU_FUND_TRANSFER_DETAILS_TXT";

    String GREEK_MENU_MF_DASHBOARD_TXT = "GREEK_MENU_MF_DASHBOARD_TXT";
    String GREEK_MENU_MF_WATCHLIST_TXT = "GREEK_MENU_MF_WATCHLIST_TXT";
    String GREEK_MENU_MF_TRANSACTION_TXT = "GREEK_MENU_MF_TRANSACTION_TXT";
    String GREEK_MENU_MF_MYACCOUNT_TXT = "GREEK_MENU_MF_MYACCOUNT_TXT";
    String GREEK_MENU_MF_REPORT_TXT = "GREEK_MENU_MF_REPORT_TXT";


}